### ISSUE TITLE
macOS builds

### ISSUE THREAD

**Issue by jacksongoode** [Vexcited/SolidCord#6]
Would be nice to test on macOS

**Comment by Vexcited** [comment]
I think I forgot to output the full `.app` for macOS but I think you can use the `.tar.gz` binaries meanwhile

(for the 0.0.7)
- m1/m2: https://github.com/Vexcited/SolidCord/releases/download/v0.0.7/SolidCord-aarch64.app.tar.gz
- intel: https://github.com/Vexcited/SolidCord/releases/download/v0.0.7/SolidCord-x86_64.app.tar.gz

**Comment by Vexcited** [comment]
Since I don't have a macOS machine under the hand, would be cool to know if there's anything special/not working well on macOS

You're free to open more issues - even though the app is in a very early development state so there's stuff that still needs to be implemented (you can still open issues even if it's planned in my head though :'))

**Comment by Vexcited** [comment]
The app is currently in a whole rewrite state, that's why I'll close this issue since macOS builds will be provided in every releases (the reason for this is that I now got a MacBook so I can finally test all these on my own !)
